# Generated by Django 3.0.7 on 2020-07-02 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=250)),
                ('post_date', models.DateField()),
                ('post_desc', models.TextField(blank=True)),
                ('featured_image', models.ImageField(blank=True, upload_to='images/')),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('event_location', models.CharField(max_length=250)),
                ('delegate_name', models.CharField(max_length=250)),
                ('company_name', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=250)),
                ('delegate_phone', models.CharField(max_length=20)),
                ('delegate_email', models.EmailField(max_length=254)),
                ('attendee_name', models.CharField(max_length=250)),
                ('attendee_phone', models.CharField(max_length=20)),
                ('attendee_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_title', models.CharField(max_length=250)),
                ('comment_date', models.DateField()),
                ('comment_desc', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(blank=True, max_length=20)),
                ('company_name', models.CharField(max_length=250)),
                ('company_name_id', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('reply_id', models.AutoField(primary_key=True, serialize=False)),
                ('reply_date', models.DateField()),
                ('reply_desc', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=250)),
                ('brand_type', models.CharField(max_length=250)),
                ('parent_company', models.CharField(max_length=250)),
                ('for_event', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='EventsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('event_desc', models.TextField(blank=True)),
                ('featured_image', models.ImageField(blank=True, upload_to='../img/events')),
                ('is_published', models.BooleanField(default=True)),
                ('location', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Delegates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegate_name', models.CharField(max_length=250)),
                ('company_name', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=250)),
                ('event_registered_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegates', to='events.EventsList')),
            ],
            options={
                'verbose_name_plural': 'Delegate',
            },
        ),
    ]
