# Generated by Django 3.0.4 on 2020-03-31 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('event_location', models.CharField(max_length=200)),
                ('event_desc', models.TextField(blank=True)),
                ('featured_image', models.ImageField(blank=True, upload_to='images/')),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
