# Generated by Django 3.0.4 on 2020-05-16 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_Attendee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegate_name', models.CharField(max_length=250)),
                ('company_name', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=250)),
                ('event_registered_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegates', to='events.EventsList')),
            ],
        ),
    ]
