# Generated by Django 3.0.6 on 2020-05-31 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_Delegates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterModelOptions(
            name='delegates',
            options={'verbose_name_plural': 'Delegate'},
        ),
        migrations.AlterField(
            model_name='eventslist',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.Location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delegates',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegates', to='events.Company'),
        ),
    ]
