# Generated by Django 3.0.6 on 2020-05-31 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200531_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslist',
            name='location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.Location'),
        ),
    ]
