# Generated by Django 3.0.6 on 2020-05-31 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200531_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegates',
            name='company_name',
            field=models.CharField(max_length=250),
        ),
    ]
