# Generated by Django 3.0.6 on 2020-05-31 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200531_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delegates',
            options={'verbose_name_plural': 'Delegate'},
        ),
    ]
