# Generated by Django 3.0.6 on 2020-05-31 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200531_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=250)),
                ('post_date', models.DateField()),
                ('post_desc', models.TextField(blank=True)),
                ('featured_image', models.ImageField(blank=True, upload_to='images/')),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=250)),
                ('brand_type', models.CharField(max_length=250)),
                ('parent_company', models.CharField(max_length=250)),
                ('for_event', models.CharField(max_length=250)),
            ],
        ),

    ]
