# Generated by Django 3.0.6 on 2020-05-31 22:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20200601_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_title', models.CharField(max_length=250)),
                ('comment_date', models.DateField()),
                ('comment_desc', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('reply_id', models.AutoField(primary_key=True, serialize=False)),
                ('reply_date', models.DateField()),
                ('reply_desc', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        
    ]
