# Generated by Django 3.0.6 on 2020-05-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_blog_sponsors'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sponsors',
            name='for_event',
            field=models.CharField(max_length=250),
        ),
    ]
