# Generated by Django 3.0.6 on 2020-05-31 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20200601_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('event_location', models.CharField(max_length=250)),
                ('delegate_name', models.CharField(max_length=250)),
                ('company_name', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=250)),
                ('delegate_phone', models.CharField(max_length=20)),
                ('delegate_email', models.EmailField(max_length=254)),
                ('attendee_name', models.CharField(max_length=250)),
                ('attendee_phone', models.CharField(max_length=20)),
                ('attendee_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
