# Generated by Django 3.0.6 on 2020-05-31 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20200601_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='id',
            new_name='company_name_id',
        ),
    ]
